heroku:
  only:
    - main
  script:
    - git checkout main
    - git remote add herouku https://heroku:380cef93-e22c-4fde-8937-3f676329bb75@git.heroku.com/projeto-2-api.git
    - git push -f heroku main